### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by lucasgrelaud** [oavkdtv/davedb-api#21]
Hi,
I noticed you've left sensitive information in the following file;
 - [MongoDB credentials](https://github.com/oavkdtv/davedb-api/blob/master/config/default.json)

This may lead to a security issue in your app, so you should remove these informations from your repository.

Regards,
Lucas GRELAUD

**Comment by juicejuz** [comment]
Hi Lucas,

Thanks for this info.

We know that we have this info there. This is Just a free dev db we not really care. and it will deleted anyway soon.

but if this is a problem we can take it out.

Cheers
Dave

**Comment by lucasgrelaud** [comment]
I wasn't sure if this app was meant to be pushed to prod or not, so i'm pleased to hear that :)
